apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 172.24.147.150:5000/nginx:v4.0.0 # {"$imagepolicy": "flux-system:nginx-latest"}
          ports:
            - containerPort: 80
